class Visitante {
  - nome: string
  - cpf: string
  - telefone: string
  + constructor(nome, documento, telefone)
}

class Quarto {
  - visitante: Visitante
  - tipo: int
  - numero: int
  - capacidade: int
  + constructor(visitante, numero, capacidade, tipo)
}

class Estacionamento {
  - visitante: Visitante
  - vaga_codigo: int
  - vagas_totais: int
  - vagas_ocupadas: int
  + constructor(vagas_totais, vagas_ocupadas, vaga_codigo)
}

class Agendamento {
  - visitante: Visitante
  - data_entrada: date
  - data_saida: date
  - quarto: Quarto
  + construtor(visitante, data, horario)
}

class Servicos {
  - quarto: Quarto
  - tipo: string
  - preco: float
  + constructor(quarto, tipo, preco)
}


Visitante --* Quarto
Visitante --* Agendamento
Quarto --* Servicos
Visitante --* Estacionamento
